// scripts/mark-pending-fixtures.ts
//
// One-off touch-up: scans corpus-discovered.ts entries, checks whether
// their fixture file exists, and marks entries without a fixture as
// skipFixture: true. Lets the accuracy test run cleanly when corpus
// expansion has outpaced the capture run (so the bulk capture can
// finish in a follow-up run without blocking CI).
//
// Usage:
//   npx tsx scripts/mark-pending-fixtures.ts

import { promises as fs } from "node:fs"
import { join, dirname } from "node:path"
import { fileURLToPath } from "node:url"
import { DISCOVERED } from "../__tests__/backtest/corpus-discovered"

const __dirname = dirname(fileURLToPath(import.meta.url))
const FIXTURES_DIR = join(__dirname, "..", "__tests__", "backtest", "fixtures")
const TARGET = join(__dirname, "..", "__tests__", "backtest", "corpus-discovered.ts")

async function main() {
  let marked = 0
  const updated = await Promise.all(DISCOVERED.map(async (e) => {
    const path = join(FIXTURES_DIR, `${e.symbol.toLowerCase()}.json`)
    let exists = false
    try { await fs.access(path); exists = true } catch { /* missing */ }
    if (!exists && !e.skipFixture) {
      marked++
      return { ...e, skipFixture: true }
    }
    return e
  }))

  // Render
  const lines: string[] = []
  lines.push("// AUTO-GENERATED by scripts/corpus-discover.ts — review before merging")
  lines.push("// Auto-labels use external DexScreener signals only (mcap, liq, age,")
  lines.push("// 24h price change). They are intentionally CONSERVATIVE: SAFE only")
  lines.push("// when overwhelming, RUG only on textbook dumps, CAUTION default. The")
  lines.push("// engine sees on-chain data the labeller can't (top wallet %, LP burn,")
  lines.push("// honeypot, GoPlus) so it has the final say — divergence between this")
  lines.push("// label and the engine surfaces in the accuracy backtest.")
  lines.push("//")
  lines.push("// Latest merge added entries from a fresh corpus-discover run on top of")
  lines.push("// the prior corpus, deduped by mint. New entries default to skipFixture")
  lines.push("// until the next capture run lands their /api/scan response.")
  lines.push("")
  lines.push("import type { CorpusEntry } from \"./corpus\"")
  lines.push("")
  lines.push("export const DISCOVERED: CorpusEntry[] = [")
  for (const e of updated) {
    const tolerated = e.tolerated && e.tolerated.length > 0
      ? `\n    tolerated: [${e.tolerated.map(v => `"${v}"`).join(", ")}],`
      : ""
    const expectedScore = e.expectedScore
      ? `\n    expectedScore: [${e.expectedScore[0]}, ${e.expectedScore[1]}],`
      : ""
    const skipFixture = e.skipFixture ? `\n    skipFixture: true, // pending first capture` : ""
    lines.push(`  {`)
    lines.push(`    ca: "${e.ca}",`)
    lines.push(`    symbol: "${e.symbol}",`)
    lines.push(`    expectedVerdict: "${e.expectedVerdict}",${tolerated}${expectedScore}`)
    lines.push(`    why: ${JSON.stringify(e.why)},`)
    lines.push(`    source: "${e.source}",${skipFixture}`)
    lines.push(`  },`)
  }
  lines.push("]")
  lines.push("")

  await fs.writeFile(TARGET, lines.join("\n"))
  const skipped = updated.filter(e => e.skipFixture).length
  const ready = updated.length - skipped
  console.log(`Touched up: ${marked} entries newly marked skipFixture`)
  console.log(`Total: ${updated.length} (${ready} fixtures ready, ${skipped} pending capture)`)
}

void main()
