// scripts/merge-corpus.ts
//
// One-off merge: takes a freshly discovered corpus (e.g. /tmp/corpus-fresh-156.ts
// dumped from a corpus-discover run) and merges its new entries into the
// existing __tests__/backtest/corpus-discovered.ts, deduping by mint.
//
// Usage:
//   npx tsx scripts/merge-corpus.ts <path-to-fresh.ts>

import { promises as fs } from "node:fs"
import { join, dirname } from "node:path"
import { fileURLToPath } from "node:url"
import { DISCOVERED as EXISTING } from "../__tests__/backtest/corpus-discovered"

const __dirname = dirname(fileURLToPath(import.meta.url))
const TARGET = join(__dirname, "..", "__tests__", "backtest", "corpus-discovered.ts")

interface CorpusEntry {
  ca: string
  symbol: string
  expectedVerdict: string
  expectedScore?: [number, number]
  tolerated?: string[]
  why: string
  source: string
  skipFixture?: boolean
}

async function main() {
  const freshPath = process.argv[2]
  if (!freshPath) {
    console.error("Usage: npx tsx scripts/merge-corpus.ts <path-to-fresh.ts>")
    process.exit(1)
  }

  // Dynamic import the fresh module
  const freshUrl = new URL(`file://${freshPath.replace(/\\/g, "/")}`)
  const freshMod = await import(freshUrl.href) as { DISCOVERED: CorpusEntry[] }
  const fresh = freshMod.DISCOVERED

  const existingByCa = new Map<string, CorpusEntry>()
  for (const e of EXISTING) existingByCa.set(e.ca, e)

  // Existing symbols (so we can suffix collisions when adding)
  const existingSymbols = new Map<string, number>()
  for (const e of EXISTING) {
    const base = e.symbol.split("_")[0]
    existingSymbols.set(base, (existingSymbols.get(base) ?? 0) + 1)
  }

  let added = 0
  let skipped = 0
  const merged: CorpusEntry[] = [...EXISTING]
  for (const f of fresh) {
    if (existingByCa.has(f.ca)) { skipped++; continue }
    // Suffix symbol if it would collide with an existing one
    let symbol = f.symbol
    const base = symbol.split("_")[0]
    if (existingSymbols.has(base)) {
      symbol = `${base}_${f.ca.slice(0, 4).toUpperCase()}`
    }
    existingSymbols.set(base, (existingSymbols.get(base) ?? 0) + 1)
    // Strip skipFixture from new entries so the default bulk capture run
    // picks them up. Existing entries keep their flags as-is (fixtures
    // already exist on disk for those — capture skips them via the
    // "fixture exists" check).
    merged.push({ ...f, symbol, skipFixture: false })
    added++
  }

  // Render
  const lines: string[] = []
  lines.push("// AUTO-GENERATED by scripts/corpus-discover.ts — review before merging")
  lines.push("// Auto-labels use external DexScreener signals only (mcap, liq, age,")
  lines.push("// 24h price change). They are intentionally CONSERVATIVE: SAFE only")
  lines.push("// when overwhelming, RUG only on textbook dumps, CAUTION default. The")
  lines.push("// engine sees on-chain data the labeller can't (top wallet %, LP burn,")
  lines.push("// honeypot, GoPlus) so it has the final say — divergence between this")
  lines.push("// label and the engine surfaces in the accuracy backtest.")
  lines.push("//")
  lines.push("// Latest merge added entries from a fresh corpus-discover run on top of")
  lines.push("// the prior corpus, deduped by mint. New entries default to skipFixture")
  lines.push("// until the next capture run lands their /api/scan response.")
  lines.push("")
  lines.push("import type { CorpusEntry } from \"./corpus\"")
  lines.push("")
  lines.push("export const DISCOVERED: CorpusEntry[] = [")
  for (const e of merged) {
    const tolerated = e.tolerated && e.tolerated.length > 0
      ? `\n    tolerated: [${e.tolerated.map(v => `"${v}"`).join(", ")}],`
      : ""
    const expectedScore = e.expectedScore
      ? `\n    expectedScore: [${e.expectedScore[0]}, ${e.expectedScore[1]}],`
      : ""
    const skipFixture = e.skipFixture ? `\n    skipFixture: true, // pending first capture` : ""
    lines.push(`  {`)
    lines.push(`    ca: "${e.ca}",`)
    lines.push(`    symbol: "${e.symbol}",`)
    lines.push(`    expectedVerdict: "${e.expectedVerdict}",${tolerated}${expectedScore}`)
    lines.push(`    why: ${JSON.stringify(e.why)},`)
    lines.push(`    source: "${e.source}",${skipFixture}`)
    lines.push(`  } as CorpusEntry,`)
  }
  lines.push("]")
  lines.push("")

  await fs.writeFile(TARGET, lines.join("\n"))
  console.log(`Merged: ${EXISTING.length} existing + ${added} new = ${merged.length} total`)
  console.log(`Skipped duplicates: ${skipped}`)
  console.log(`Wrote: ${TARGET}`)
}

void main()
