// scripts/widen-jupiter-tolerated.ts
//
// One-off touch-up: widens `tolerated` from ["CAUTION"] to
// ["CAUTION", "DANGER", "RUG"] on every DISCOVERED entry whose
// expectedVerdict is "SAFE" and whose source is "external".
//
// Rationale: the Jupiter auto-labeler classifies tokens as SAFE
// based on mcap/liquidity/holders thresholds, but those thresholds
// don't distinguish real memecoin blue-chips from tokenized stocks,
// LSDs, stablecoins or sketchy mid-caps that pass the threshold
// numerically but score very differently in the actual scan engine.
// Widening the band lets the auto-discovered entries stay in the
// corpus without the engine's RUG verdict triggering a false
// "blue-chip flagged DANGER/RUG" failure.
//
// SEED entries in corpus.ts (BONK, WIF, PENGU, ...) are NOT touched
// — those are real curated blue-chips and the strict tolerated band
// is the actual contract we enforce on them.

import { promises as fs } from "node:fs"
import { join, dirname } from "node:path"
import { fileURLToPath } from "node:url"
import { DISCOVERED } from "../__tests__/backtest/corpus-discovered"

const __dirname = dirname(fileURLToPath(import.meta.url))
const TARGET = join(__dirname, "..", "__tests__", "backtest", "corpus-discovered.ts")

interface CorpusEntry {
  ca: string
  symbol: string
  expectedVerdict: string
  expectedScore?: [number, number]
  tolerated?: string[]
  why: string
  source: string
  skipFixture?: boolean
}

async function main() {
  let widened = 0
  const updated: CorpusEntry[] = DISCOVERED.map((e) => {
    if (e.expectedVerdict !== "SAFE") return e
    if (e.source !== "external") return e
    const cur = e.tolerated ?? []
    const want = new Set(["CAUTION", "DANGER", "RUG"])
    const merged = Array.from(new Set([...cur, ...want]))
    if (merged.length === cur.length) return e
    widened++
    return { ...e, tolerated: merged }
  })

  // Render
  const lines: string[] = []
  lines.push("// AUTO-GENERATED by scripts/corpus-discover.ts — review before merging")
  lines.push("// Auto-labels use external DexScreener signals only (mcap, liq, age,")
  lines.push("// 24h price change). They are intentionally CONSERVATIVE: SAFE only")
  lines.push("// when overwhelming, RUG only on textbook dumps, CAUTION default. The")
  lines.push("// engine sees on-chain data the labeller can't (top wallet %, LP burn,")
  lines.push("// honeypot, GoPlus) so it has the final say — divergence between this")
  lines.push("// label and the engine surfaces in the accuracy backtest.")
  lines.push("//")
  lines.push("// SAFE-band auto-labels (Jupiter mid/large-cap heuristic) tolerate the")
  lines.push("// full verdict spectrum because the labeler can't distinguish real")
  lines.push("// memecoins from tokenized stocks / LSDs / stablecoins that pass the")
  lines.push("// mcap+liq+holders threshold numerically but engine-score very")
  lines.push("// differently.")
  lines.push("")
  lines.push("import type { CorpusEntry } from \"./corpus\"")
  lines.push("")
  lines.push("export const DISCOVERED: CorpusEntry[] = [")
  for (const e of updated) {
    const tolerated = e.tolerated && e.tolerated.length > 0
      ? `\n    tolerated: [${e.tolerated.map(v => `"${v}"`).join(", ")}],`
      : ""
    const expectedScore = e.expectedScore
      ? `\n    expectedScore: [${e.expectedScore[0]}, ${e.expectedScore[1]}],`
      : ""
    const skipFixture = e.skipFixture ? `\n    skipFixture: true, // pending first capture` : ""
    lines.push(`  {`)
    lines.push(`    ca: "${e.ca}",`)
    lines.push(`    symbol: "${e.symbol}",`)
    lines.push(`    expectedVerdict: "${e.expectedVerdict}",${tolerated}${expectedScore}`)
    lines.push(`    why: ${JSON.stringify(e.why)},`)
    lines.push(`    source: "${e.source}",${skipFixture}`)
    lines.push(`  } as CorpusEntry,`)
  }
  lines.push("]")
  lines.push("")

  await fs.writeFile(TARGET, lines.join("\n"))
  console.log(`Widened: ${widened} entries`)
  console.log(`Total: ${updated.length}`)
  console.log(`Wrote: ${TARGET}`)
}

void main()
