// AUTO-GENERATED by scripts/corpus-discover.ts — review before merging
// Auto-labels use external DexScreener signals only (mcap, liq, age,
// 24h price change). They are intentionally CONSERVATIVE: SAFE only
// when overwhelming, RUG only on textbook dumps, CAUTION default. The
// engine sees on-chain data the labeller can't (top wallet %, LP burn,
// honeypot, GoPlus) so it has the final say — divergence between this
// label and the engine surfaces in the accuracy backtest.

import type { CorpusEntry } from "./corpus"

export const DISCOVERED: CorpusEntry[] = [
  {
    ca: "FU9s7E8zSczG1GXuy2u9n3VNgH6scJz9AprbxNtZpump",
    symbol: "SVE",
    expectedVerdict: "RUG",
    tolerated: ["DANGER"],
    expectedScore: [0, 400],
    why: "24h drop -96%, liq $3.8k — textbook rug.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "DzEdjffc7JkbkuDUkrf98njJ7KBVzabqUw5hej4Epump",
    symbol: "KILLGPT",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER"],
    expectedScore: [300, 900],
    why: "mcap $0.60M, age 0d, liq $63k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "HDCaUHXLRsZCwdkgx7kM23ggojN5s6LagKLv8TEapump",
    symbol: "SCAMODEI",
    expectedVerdict: "RUG",
    tolerated: ["DANGER"],
    expectedScore: [0, 400],
    why: "24h drop -95%, liq $4.7k — textbook rug.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "7EV9ShfBB5NGtGcFVBQPVUVVtW3D6Emr3dPmh8rBpump",
    symbol: "PEEWELL",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION"],
    expectedScore: [100, 600],
    why: "liq $11.8k, age 2d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "DACYVx34V5aQaehN3MZGYxPfoyQYHZSnFAFw3T2Vbonk",
    symbol: "IMOUT",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER"],
    expectedScore: [300, 900],
    why: "mcap $0.33M, age 7d, liq $72k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "E4xqRvahx9UdN5Unc2v5fmrkSK35UYZqi4gGJsbDpump",
    symbol: "SCAMPOWEL",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION"],
    expectedScore: [100, 600],
    why: "liq $8.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "8SC3JXVf3UT5wEM9x48B1jVzWUeDgZiZdrrhN3zJpump",
    symbol: "SCAMDEX",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER"],
    expectedScore: [300, 900],
    why: "mcap $0.58M, age 0d, liq $67k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "Hon2rHAiqkcDtUzL5gA2vjXPr7T1MPCK2UT2AHKCpump",
    symbol: "MAGA",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER"],
    expectedScore: [300, 900],
    why: "mcap $16.87M, age 66d, liq $434k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "97tBZooZkwM1VfuCHYqhaAzZ2Y7TEAfVhJEW9MLbpump",
    symbol: "LUCA",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION"],
    expectedScore: [100, 600],
    why: "liq $6.5k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "6qbh9jzbzHwKGH5gSXkWj5R7CjnbiVLRFs55cJx2pump",
    symbol: "SUICIDEGPT",
    expectedVerdict: "RUG",
    tolerated: ["DANGER"],
    expectedScore: [0, 400],
    why: "24h drop -94%, liq $4.1k — textbook rug.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "3MZH44EYTvaStS4PtYrzkqa6FqzhhpBRXYBnnMAupump",
    symbol: "SCAMGUY",
    expectedVerdict: "RUG",
    tolerated: ["DANGER"],
    expectedScore: [0, 400],
    why: "24h drop -95%, liq $3.5k — textbook rug.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "DVtBMoubZfcqLyMzM6QbVMTGigGBsS9JAqUPfLXBpump",
    symbol: "USC",
    expectedVerdict: "RUG",
    tolerated: ["DANGER"],
    expectedScore: [0, 400],
    why: "24h drop -94%, liq $3.8k — textbook rug.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "3M3E4gf17jjeeZomna61H4rhMs5HVY8ypD7mUdZRpump",
    symbol: "WLD",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER"],
    expectedScore: [300, 900],
    why: "mcap $0.05M, age 0d, liq $19k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "CLVH4ob7p2afvG9fVSp5MQNw2rjXD7uR1PmfhiM7pump",
    symbol: "SCAMAI",
    expectedVerdict: "RUG",
    tolerated: ["DANGER"],
    expectedScore: [0, 400],
    why: "24h drop -94%, liq $3.8k — textbook rug.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "HYjNV846yU9rpG2ffMG8TaHJdBUWm1tPuttj2Dmkpump",
    symbol: "UNCSCAM",
    expectedVerdict: "RUG",
    tolerated: ["DANGER"],
    expectedScore: [0, 400],
    why: "24h drop -94%, liq $3.6k — textbook rug.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "3TYgKwkE2Y3rxdw9osLRSpxpXmSC1C1oo19W9KHspump",
    symbol: "BULL",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER"],
    expectedScore: [300, 900],
    why: "mcap $5.13M, age 36d, liq $284k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "HdRFFy6Sm42rDAPLGRAZ1YymtpLukziwBrE9QGs4pump",
    symbol: "CRACKROCK",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER"],
    expectedScore: [300, 900],
    why: "mcap $0.22M, age 0d, liq $37k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "12cNc76MT4H2F6CTndFNWpnoTwY6qz4vo2J9oGhFpump",
    symbol: "SKEM",
    expectedVerdict: "RUG",
    tolerated: ["DANGER"],
    expectedScore: [0, 400],
    why: "24h drop -95%, liq $3.5k — textbook rug.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "9F7YBM7emfWeJUxFKdH6ECYm6tB67869EcC4qmGzpump",
    symbol: "SCAM",
    expectedVerdict: "RUG",
    tolerated: ["DANGER"],
    expectedScore: [0, 400],
    why: "24h drop -95%, liq $3.2k — textbook rug.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "BFiGUxnidogqcZAPVPDZRCfhx3nXnFLYqpQUaUGpump",
    symbol: "SPIKE",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER"],
    expectedScore: [300, 900],
    why: "mcap $10.50M, age 20d, liq $372k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "BVzgTYPqV6ipEG4ixaQGfJvtYrs6kYJAt2HPBDMvpump",
    symbol: "SCAMGPT",
    expectedVerdict: "RUG",
    tolerated: ["DANGER"],
    expectedScore: [0, 400],
    why: "24h drop -95%, liq $3.3k — textbook rug.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "5gTPspC2ricuGWiYQ4Ghausg8fsq7uCrGgSVACatcoin",
    symbol: "CATCOIN",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER"],
    expectedScore: [300, 900],
    why: "mcap $0.40M, age 4d, liq $58k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "59Ntdzm81rWKBshmuhJmuPFzczUy5e4zow2NNrpcDXTy",
    symbol: "SES",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER"],
    expectedScore: [300, 900],
    why: "mcap $0.56M, age 0d, liq $37k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "ByyMCyATC6j92DFYGCC45qnCinpbHpHVEPPQZf2ezST6",
    symbol: "TEG",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER"],
    expectedScore: [300, 900],
    why: "mcap $0.61M, age 2d, liq $174k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "AABEk6vPpgLLoGGqRC4SrSTuZYywLyyPyfcAfvRzpump",
    symbol: "BOOBIO",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER"],
    expectedScore: [300, 900],
    why: "mcap $0.06M, age 0d, liq $19k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "CAjtTHvC878f8cZ4zEwdvgjkjFM7rbYN8Mb1go1cpump",
    symbol: "DUMBMONEY",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER"],
    expectedScore: [300, 900],
    why: "mcap $0.31M, age 14d, liq $67k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "7nZuYZYZnof9gF3zr9QhdnxpQ1mTM8LN3VaJuhrGbonk",
    symbol: "RCON",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER"],
    expectedScore: [300, 900],
    why: "mcap $0.39M, age 234d, liq $61k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "23SSf55rhFSadnESqVtnb7KW5AjdW19X3i2M9Bvupump",
    symbol: "ELANVSSCAM",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "4syGYCWUrRU8po4DQZgPgpzhZG8nZXQoGu4Jf7fppump",
    symbol: "SCAMUSK",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "HmBdm8vbisABUjkxms6ZUnoaXbfwFM6ymxShWfAENaoi",
    symbol: "EITHER",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER"],
    expectedScore: [300, 900],
    why: "mcap $25.70M, age 35d, liq $429k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "9oxGicd5KXNcthYM6yD23X9zcznQVnHjrAEN38fFpump",
    symbol: "BIOLLM",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER"],
    expectedScore: [300, 900],
    why: "mcap $0.55M, age 56d, liq $83k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "96qJmCKtj9E5fiehGToQ69bwyiw9q86y7q4gAGznpump",
    symbol: "MESSI",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "tUAxFzG84g9X8rXkk2KWgrKdaVSsc59KrDEPiv3pump",
    symbol: "DOGMCOIN",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "9QLrH5vE51uNavc9VWAA5GgjXzXDLNk1va6iWYJyEPt3",
    symbol: "WXG",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER"],
    expectedScore: [300, 900],
    why: "mcap $0.10M, age 135d, liq $18k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "3ZcEqsgJZxy5pER4XBfa2UbjBmRAgG96nUrTATfMpump",
    symbol: "WHITEBOY",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 4d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "APJ8ovk6mqScmtezgtMcMGxkiB5PGwcLmgz343Rkpump",
    symbol: "SCAMCOIN",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "7soYuSPe1LaJ9V37W7ZGDB5Xwxi41LUWjRT3AEQGpump",
    symbol: "WOLVERINE",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION"],
    expectedScore: [100, 600],
    why: "liq $10.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "52nVoVk3BimAtvu2y9q1gnxqgR8pmjcc3v3byGnCuBa",
    symbol: "SCUBA",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER"],
    expectedScore: [300, 900],
    why: "mcap $0.32M, age 54d, liq $66k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "GC3T8XboCofhBPs5U48DJgp6cxxMeu1CBZXgB2dopump",
    symbol: "LITH",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION"],
    expectedScore: [100, 600],
    why: "liq $6.6k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "7UFSoXdgwyzRha6gaUKvj97my2244HtSTh3u1jwGpump",
    symbol: "67SCAM",
    expectedVerdict: "RUG",
    tolerated: ["DANGER"],
    expectedScore: [0, 400],
    why: "24h drop -96%, liq $3.4k — textbook rug.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "2JEQfsUPkc3ozgQwnubvaeQJs139ufAm3YSWTY1spump",
    symbol: "ELON",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION"],
    expectedScore: [100, 600],
    why: "liq $6.6k, age 1d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "GUfyGEF62BUUqj5f5PveZknhBQMWWFSXm2jqAdikpump",
    symbol: "MUSK",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER"],
    expectedScore: [300, 900],
    why: "mcap $0.06M, age 0d, liq $22k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "Gq32ooCHXFPzjWnDz4ZFpdoaAfLewyGEZNa2mSKCpump",
    symbol: "RUSTFANG",
    expectedVerdict: "RUG",
    tolerated: ["DANGER"],
    expectedScore: [0, 400],
    why: "24h drop -95%, liq $3.3k — textbook rug.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "DXcwhg1MwrResr1CoaBuhnnHmcx222ntZAgRd28Jpump",
    symbol: "SCAM_DXCW",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER"],
    expectedScore: [300, 900],
    why: "mcap $0.26M, age 1d, liq $46k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "6CB7zLaYvkHUDYcccDFWgi9wK5a7M9yz1Ph6JsTHpump",
    symbol: "GFYS",
    expectedVerdict: "RUG",
    tolerated: ["DANGER"],
    expectedScore: [0, 400],
    why: "24h drop -95%, liq $3.4k — textbook rug.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "AdSmSiEDQQjzpgBHKn8kY5sWfv5HfnSVRRcSDoWZpump",
    symbol: "WHEN",
    expectedVerdict: "RUG",
    tolerated: ["DANGER"],
    expectedScore: [0, 400],
    why: "24h drop -93%, liq $3.7k — textbook rug.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "FFvp48WygUSxCCNP3n9Zu5G7F2yatwXQHbpD2Mkkpump",
    symbol: "SKIBIDI",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER"],
    expectedScore: [300, 900],
    why: "mcap $0.70M, age 17d, liq $94k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "9tCjcZFwaqMFSFkiYDRAGd3kxChxVguHDCREb6eSpump",
    symbol: "WIF2",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER"],
    expectedScore: [300, 900],
    why: "mcap $0.04M, age 7d, liq $20k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "BU9NRdPU4JnLEzBcYjzyGNBUzzXhCaU6nfEWnQYpump",
    symbol: "GEMINI",
    expectedVerdict: "RUG",
    tolerated: ["DANGER"],
    expectedScore: [0, 400],
    why: "24h drop -92%, liq $4.0k — textbook rug.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "54y9dpTbM2KccpybBwFzCxCQ6ey2E7mRT6SY5pScpump",
    symbol: "100",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION"],
    expectedScore: [100, 600],
    why: "liq $10.1k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "2agXhep8J9sa5kQNNQzzE9JYDVNQgV3DUiWRazAQDckV",
    symbol: "AGUNT",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION"],
    expectedScore: [100, 600],
    why: "liq $10.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "A7NQr2P7SXZBxVTnAT2NG2tiko1Kt9gNrb5SjB9xiStu",
    symbol: "BEEKEEPER",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER"],
    expectedScore: [300, 900],
    why: "mcap $97.99M, age 0d, liq $182k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "B4yPHT6LHHWaVYzF4ahVNH7aDNWsX6soaKEcPEeQpump",
    symbol: "PULYMERKET",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "4gA2TTibyLhLHrwkAZgsqCfmQ5jRKbzEVoDdn4k9pump",
    symbol: "APHEX",
    expectedVerdict: "RUG",
    tolerated: ["DANGER"],
    expectedScore: [0, 400],
    why: "24h drop -95%, liq $3.5k — textbook rug.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "7bTj4pu4mzwx1Gn9obxStyUoJzdNk53UDhTYgyAupump",
    symbol: "COLOSSUS",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "GmdK57mqDyPPgh5Un8ajangHtNH8P1kqPYKvA48gpump",
    symbol: "SCAMTIDE",
    expectedVerdict: "RUG",
    tolerated: ["DANGER"],
    expectedScore: [0, 400],
    why: "24h drop -95%, liq $3.2k — textbook rug.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "Cnfqg24RwATQFZke94xfAJ1bAYGkz1u1BgaHkswwpump",
    symbol: "UWU",
    expectedVerdict: "RUG",
    tolerated: ["DANGER"],
    expectedScore: [0, 400],
    why: "24h drop -85%, liq $5.6k — textbook rug.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "4Zn4ZtZEPo9Eud5s23PZtF19ostY5FBRs6Pf5cJSpump",
    symbol: "APHEX_4ZN4",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER"],
    expectedScore: [300, 900],
    why: "mcap $0.05M, age 0d, liq $19k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "25XNzUz9spyy8W4KFeH6CugVotzLE3iAueNyRxBQpump",
    symbol: "BIOHEKUR",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "6sg2nHWqZBX5bXXfm2LwxZhdPiLhois688bPAtmTpump",
    symbol: "CAR",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "C5n2iZVhuQBLdkTAVppcwPWUDegWo8RoNAbaN5CoQonX",
    symbol: "SPOK",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "CN7Ws9pVfLSpfjWSxZYJm69Uqoq6PCGmMjqGYamspump",
    symbol: "GUSTA",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "FMeUYuncPhTiCV5kbCeE7g7Mo6kXRoDWMzTTngyUpump",
    symbol: "BEE",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "3BRQ9W9ZVm7qmvW9PUe2CpBHBdeKEnMLgREu7wLgpump",
    symbol: "AI",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION"],
    expectedScore: [100, 600],
    why: "liq $13.8k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "6rv8RwPcKGjRGyiGviPqERmYnE1XLQRMm8B7BRAvbrrr",
    symbol: "FAX",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER"],
    expectedScore: [300, 900],
    why: "mcap $0.13M, age 0d, liq $27k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "CjECbd7FLuuY2ZCng2WDeQd1fMhKDHof9mPwtoNQpump",
    symbol: "BEE_CJEC",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "hLJt7kmrvmiU7gpxzWkJHyxb7QaJ9qHMFmMEz3cpump",
    symbol: "LIBERTY",
    expectedVerdict: "RUG",
    tolerated: ["DANGER"],
    expectedScore: [0, 400],
    why: "24h drop -93%, liq $4.0k — textbook rug.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "5z3EqYQo9HiCEs3R84RCDMu2n7anpDMxRhdK8PSWmrRC",
    symbol: "PONKE",
    expectedVerdict: "SAFE",
    tolerated: ["CAUTION", "DANGER"],
    expectedScore: [650, 1000],
    why: "mcap $15.1M, age 856d, liq $1413k — solid established profile.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "5HV956n7UQT1XdJzv43fHPocest5YAmi9ipsuiJx7zt7",
    symbol: "MEMECOIN",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER"],
    expectedScore: [300, 900],
    why: "mcap $0.06M, age 379d, liq $45k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "CeK6k4BMmiqkxkzYAbQuUp3hrVFSHxuQ1LJXmNybc3vz",
    symbol: "BINK",
    expectedVerdict: "SAFE",
    tolerated: ["CAUTION", "DANGER"],
    expectedScore: [650, 1000],
    why: "mcap $11.1M, age 771d, liq $507k — solid established profile.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "HgBRWfYxEfvPhtqkaeymCQtHCrKE46qQ43pKe8HCpump",
    symbol: "BERT",
    expectedVerdict: "SAFE",
    tolerated: ["CAUTION", "DANGER"],
    expectedScore: [650, 1000],
    why: "mcap $11.1M, age 574d, liq $816k — solid established profile.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "Df6yfrKC8kZE3KNkrHERKzAetSxbrWeniQfyJY4Jpump",
    symbol: "CHILLGUY",
    expectedVerdict: "SAFE",
    tolerated: ["CAUTION", "DANGER"],
    expectedScore: [650, 1000],
    why: "mcap $11.1M, age 528d, liq $1111k — solid established profile.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "1Qf8gESP4i6CFNWerUSDdLKJ9U1LpqTYvjJ2MM4pain",
    symbol: "PAIN",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER"],
    expectedScore: [300, 900],
    why: "mcap $3.85M, age 433d, liq $2443k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "AyrQpt5xsVYiN4BqgZdd2tZJAWswT9yLUZmP1jKqpump",
    symbol: "JOBCOIN",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER"],
    expectedScore: [300, 900],
    why: "mcap $3.84M, age 378d, liq $297k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "mpoxP5wyoR3eRW8L9bZjGPFtCsmX8WcqU5BHxFW1xkn",
    symbol: "POX",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER"],
    expectedScore: [300, 900],
    why: "mcap $1.77M, age 608d, liq $86k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "6yjNqPzTSanBWSa6dxVEgTjePXBrZ2FoHLDQwYwEsyM6",
    symbol: "CHUD",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER"],
    expectedScore: [300, 900],
    why: "mcap $1.77M, age 723d, liq $307k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "9raUVuzeWUk53co63M4WXLWPWE4Xc6Lpn7RS9dnkpump",
    symbol: "V2EX",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER"],
    expectedScore: [300, 900],
    why: "mcap $1.73M, age 295d, liq $183k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "5SVG3T9CNQsm2kEwzbRq6hASqh1oGfjqTtLXYUibpump",
    symbol: "SIGMA",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER"],
    expectedScore: [300, 900],
    why: "mcap $1.71M, age 655d, liq $374k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "CreiuhfwdWCN5mJbMJtA9bBpYQrQF2tCBuZwSPWfpump",
    symbol: "PYTHIA",
    expectedVerdict: "SAFE",
    tolerated: ["CAUTION"],
    expectedScore: [750, 1000],
    why: "mcap $58M, age 63d, liq $3.3M — established blue-chip.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "CTgiaZUK12kCcB8sosn4Nt2NZtzLgtPqDwyQyr2syATC",
    symbol: "BITCOIN",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER"],
    expectedScore: [300, 900],
    why: "mcap $0.26M, age 530d, liq $103k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "2nnrviYJRLcf2bXAxpKTRXzccoDbwaP4vzuGUG75Jo45",
    symbol: "KENDU",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER"],
    expectedScore: [300, 900],
    why: "mcap $3.22M, age 470d, liq $33k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "GQz5ThKHNcuAvMKA8rCPSdoFUoApk9Fi8qB9m3Gqpump",
    symbol: "SAN",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER"],
    expectedScore: [300, 900],
    why: "mcap $1.26M, age 80d, liq $94k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "6iA73gWCKkLWKbVr8rgibV57MMRxzsaqS9cWpgKBpump",
    symbol: "",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER"],
    expectedScore: [300, 900],
    why: "mcap $1.26M, age 62d, liq $152k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "Gaqt6hKqBSRga8pfJ43CfTbc9ZGw8ostPnjytfbNpump",
    symbol: "JINDO",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER"],
    expectedScore: [300, 900],
    why: "mcap $1.19M, age 155d, liq $88k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
]
