// AUTO-GENERATED by scripts/corpus-discover.ts — review before merging
// Auto-labels use external DexScreener signals only (mcap, liq, age,
// 24h price change). They are intentionally CONSERVATIVE: SAFE only
// when overwhelming, RUG only on textbook dumps, CAUTION default. The
// engine sees on-chain data the labeller can't (top wallet %, LP burn,
// honeypot, GoPlus) so it has the final say — divergence between this
// label and the engine surfaces in the accuracy backtest.

import type { CorpusEntry } from "./corpus"

export const DISCOVERED: CorpusEntry[] = [
  {
    ca: "7EV9ShfBB5NGtGcFVBQPVUVVtW3D6Emr3dPmh8rBpump",
    symbol: "PEEWELL",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION"],
    expectedScore: [100, 600],
    why: "liq $10.5k, age 2d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "FU9s7E8zSczG1GXuy2u9n3VNgH6scJz9AprbxNtZpump",
    symbol: "SVE",
    expectedVerdict: "RUG",
    tolerated: ["DANGER"],
    expectedScore: [0, 400],
    why: "24h drop -96%, liq $3.8k — textbook rug.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "HDCaUHXLRsZCwdkgx7kM23ggojN5s6LagKLv8TEapump",
    symbol: "SCAMODEI",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER"],
    expectedScore: [300, 900],
    why: "mcap $0.29M, age 0d, liq $44k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "DACYVx34V5aQaehN3MZGYxPfoyQYHZSnFAFw3T2Vbonk",
    symbol: "IMOUT",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER"],
    expectedScore: [300, 900],
    why: "mcap $0.32M, age 7d, liq $72k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "E4xqRvahx9UdN5Unc2v5fmrkSK35UYZqi4gGJsbDpump",
    symbol: "SCAMPOWEL",
    expectedVerdict: "RUG",
    tolerated: ["DANGER"],
    expectedScore: [0, 400],
    why: "24h drop -94%, liq $3.6k — textbook rug.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "8SC3JXVf3UT5wEM9x48B1jVzWUeDgZiZdrrhN3zJpump",
    symbol: "SCAMDEX",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER"],
    expectedScore: [300, 900],
    why: "mcap $0.41M, age 0d, liq $52k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "Hon2rHAiqkcDtUzL5gA2vjXPr7T1MPCK2UT2AHKCpump",
    symbol: "MAGA",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER"],
    expectedScore: [300, 900],
    why: "mcap $16.64M, age 66d, liq $430k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "97tBZooZkwM1VfuCHYqhaAzZ2Y7TEAfVhJEW9MLbpump",
    symbol: "LUCA",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION"],
    expectedScore: [100, 600],
    why: "liq $10.2k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "6qbh9jzbzHwKGH5gSXkWj5R7CjnbiVLRFs55cJx2pump",
    symbol: "SUICIDEGPT",
    expectedVerdict: "RUG",
    tolerated: ["DANGER"],
    expectedScore: [0, 400],
    why: "24h drop -94%, liq $4.1k — textbook rug.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "3MZH44EYTvaStS4PtYrzkqa6FqzhhpBRXYBnnMAupump",
    symbol: "SCAMGUY",
    expectedVerdict: "RUG",
    tolerated: ["DANGER"],
    expectedScore: [0, 400],
    why: "24h drop -95%, liq $3.4k — textbook rug.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "34q2KmCvapecJgR6ZrtbCTrzZVtkt3a5mHEA3TuEsWYb",
    symbol: "LOL",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER"],
    expectedScore: [300, 900],
    why: "mcap $2.45M, age 40d, liq $249k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "DVtBMoubZfcqLyMzM6QbVMTGigGBsS9JAqUPfLXBpump",
    symbol: "USC",
    expectedVerdict: "RUG",
    tolerated: ["DANGER"],
    expectedScore: [0, 400],
    why: "24h drop -94%, liq $3.7k — textbook rug.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "CLVH4ob7p2afvG9fVSp5MQNw2rjXD7uR1PmfhiM7pump",
    symbol: "SCAMAI",
    expectedVerdict: "RUG",
    tolerated: ["DANGER"],
    expectedScore: [0, 400],
    why: "24h drop -94%, liq $3.7k — textbook rug.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "HYjNV846yU9rpG2ffMG8TaHJdBUWm1tPuttj2Dmkpump",
    symbol: "UNCSCAM",
    expectedVerdict: "RUG",
    tolerated: ["DANGER"],
    expectedScore: [0, 400],
    why: "24h drop -94%, liq $3.6k — textbook rug.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "3TYgKwkE2Y3rxdw9osLRSpxpXmSC1C1oo19W9KHspump",
    symbol: "BULL",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER"],
    expectedScore: [300, 900],
    why: "mcap $5.37M, age 36d, liq $289k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "3M3E4gf17jjeeZomna61H4rhMs5HVY8ypD7mUdZRpump",
    symbol: "WLD",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER"],
    expectedScore: [300, 900],
    why: "mcap $0.06M, age 0d, liq $21k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "HdRFFy6Sm42rDAPLGRAZ1YymtpLukziwBrE9QGs4pump",
    symbol: "CRACKROCK",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER"],
    expectedScore: [300, 900],
    why: "mcap $0.21M, age 0d, liq $36k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "12cNc76MT4H2F6CTndFNWpnoTwY6qz4vo2J9oGhFpump",
    symbol: "SKEM",
    expectedVerdict: "RUG",
    tolerated: ["DANGER"],
    expectedScore: [0, 400],
    why: "24h drop -95%, liq $3.5k — textbook rug.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "9F7YBM7emfWeJUxFKdH6ECYm6tB67869EcC4qmGzpump",
    symbol: "SCAM",
    expectedVerdict: "RUG",
    tolerated: ["DANGER"],
    expectedScore: [0, 400],
    why: "24h drop -95%, liq $3.3k — textbook rug.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "BFiGUxnidogqcZAPVPDZRCfhx3nXnFLYqpQUaUGpump",
    symbol: "SPIKE",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER"],
    expectedScore: [300, 900],
    why: "mcap $11.09M, age 20d, liq $381k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "BVzgTYPqV6ipEG4ixaQGfJvtYrs6kYJAt2HPBDMvpump",
    symbol: "SCAMGPT",
    expectedVerdict: "RUG",
    tolerated: ["DANGER"],
    expectedScore: [0, 400],
    why: "24h drop -95%, liq $3.2k — textbook rug.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "5gTPspC2ricuGWiYQ4Ghausg8fsq7uCrGgSVACatcoin",
    symbol: "CATCOIN",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER"],
    expectedScore: [300, 900],
    why: "mcap $0.42M, age 4d, liq $60k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "59Ntdzm81rWKBshmuhJmuPFzczUy5e4zow2NNrpcDXTy",
    symbol: "SES",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER"],
    expectedScore: [300, 900],
    why: "mcap $0.68M, age 0d, liq $42k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "ByyMCyATC6j92DFYGCC45qnCinpbHpHVEPPQZf2ezST6",
    symbol: "TEG",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER"],
    expectedScore: [300, 900],
    why: "mcap $0.56M, age 2d, liq $166k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "CAjtTHvC878f8cZ4zEwdvgjkjFM7rbYN8Mb1go1cpump",
    symbol: "DUMBMONEY",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER"],
    expectedScore: [300, 900],
    why: "mcap $0.28M, age 14d, liq $63k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "AABEk6vPpgLLoGGqRC4SrSTuZYywLyyPyfcAfvRzpump",
    symbol: "BOOBIO",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER"],
    expectedScore: [300, 900],
    why: "mcap $0.06M, age 0d, liq $19k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "23SSf55rhFSadnESqVtnb7KW5AjdW19X3i2M9Bvupump",
    symbol: "ELANVSSCAM",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "7nZuYZYZnof9gF3zr9QhdnxpQ1mTM8LN3VaJuhrGbonk",
    symbol: "RCON",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER"],
    expectedScore: [300, 900],
    why: "mcap $0.38M, age 233d, liq $61k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "DhLS8o4f86zVs66J1Ma1cb1x2C2KaBHKxJ8xjpV8uzLR",
    symbol: "5",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "EqYU36vG9xrhuhLvqRiA4HpqrQcXquxyAE3BzZ7rXJNE",
    symbol: "ERIC",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "ncSWfH7ZjTK5Ebo43YekNBHLQJwwhypb97Ta3Qupump",
    symbol: "BEEPE",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "7mJ4tTSsL63fa69qkdDbw4fhx6SPzfA8uS4bVisStfi4",
    symbol: "BEEKEEPER",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER"],
    expectedScore: [300, 900],
    why: "mcap $0.27M, age 0d, liq $44k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "GC3T8XboCofhBPs5U48DJgp6cxxMeu1CBZXgB2dopump",
    symbol: "LITH",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "DTfN4DotNupzDbqpg6dX4jfXekB5vVkePxjuyivJpump",
    symbol: "BEE",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER"],
    expectedScore: [300, 900],
    why: "mcap $1.01M, age 0d, liq $131k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "BDsKirdnNnqcMLpdMTnwXqNPfMWyMLQpxBu9D4zYpump",
    symbol: "CHUDGPT",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "WaYLBx42GBPHbvP8Mt2vKrJ4ofriaBnAmAEWP2Spump",
    symbol: "TUK",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "4vuGayUwhShVJUZqBcAMSv92mTLjasu9mCwbGr7Tbonk",
    symbol: "POOF",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION"],
    expectedScore: [100, 600],
    why: "liq $13.8k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "HJXaVnpSptn4YWvTK4EjpsoEvFdMzK5XPEAE9CC1pump",
    symbol: "DADI",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION"],
    expectedScore: [100, 600],
    why: "liq $9.9k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "3twD5YXtXDaPHPucNFp8Qu8cSmG7EDELmwxUMoNYpump",
    symbol: "LACHACHU",
    expectedVerdict: "RUG",
    tolerated: ["DANGER"],
    expectedScore: [0, 400],
    why: "24h drop -95%, liq $3.2k — textbook rug.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "7UFSoXdgwyzRha6gaUKvj97my2244HtSTh3u1jwGpump",
    symbol: "67SCAM",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER"],
    expectedScore: [300, 900],
    why: "mcap $0.22M, age 0d, liq $37k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "3WtsmC5wbrptHnSv59HX5vYzzCUs4FJSVk7gC1ofMMS7",
    symbol: "WLD_3WTS",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "BZHkLAqtevfSmb4BABBhJaUKkFiUe7mGnqW3oAtdpump",
    symbol: "BOP",
    expectedVerdict: "RUG",
    tolerated: ["DANGER"],
    expectedScore: [0, 400],
    why: "24h drop -95%, liq $3.3k — textbook rug.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "4wPP2Vc4S9CV24Zb3R5RGqdvRgfuR1vZtuLEVc3Rpump",
    symbol: "BOBBY",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "2iB7DnDBLFKRTVShXdcyX9jS8S5gWRicEbu3e2Uypump",
    symbol: "ZUMI",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION"],
    expectedScore: [100, 600],
    why: "liq $6.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "HmnHcCkzbF3Wh4TGhmmgJNuLRSHTSzsjk6axAkiEbrrr",
    symbol: "GOYFATHER",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION"],
    expectedScore: [100, 600],
    why: "liq $5.3k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "9yYaETW5zePWSpNQyrS1hHXggsH33b3cGQo2o94Ypump",
    symbol: "ISO",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "2iFuvGw8tno9Z1Jy7esgQsVpz42zdy91LtpGjdQcpump",
    symbol: "CAPSHIT",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "6TrbqHdEfaDuR29idj76ZD95fn3UUFc9UTK7jTJCpump",
    symbol: "DRILLPIG",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "7soYuSPe1LaJ9V37W7ZGDB5Xwxi41LUWjRT3AEQGpump",
    symbol: "WOLVERINE",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER"],
    expectedScore: [300, 900],
    why: "mcap $0.05M, age 0d, liq $17k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "2kCrLcnZ7wx6waUgeo9PR6o7EGzmr2Ee9ZuKZuRRpump",
    symbol: "POOF_2KCR",
    expectedVerdict: "RUG",
    tolerated: ["DANGER"],
    expectedScore: [0, 400],
    why: "24h drop -90%, liq $4.5k — textbook rug.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "8KQhezEXnYzBG1i9Tb2GZ9e1E1msSJsmBa71C3XN6hRY",
    symbol: "ANONYMOOS",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "3oTVMdh67zyyg67BCoP7AyGaM6Rj8i4jUzpJoKtwpump",
    symbol: "MEMESCORE",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "Gx5ut9ZMkdpmoimFgpqT8ndiD2irdFwtRhz6n54Gpump",
    symbol: "NEXRGE",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "FcckraqMQvG3z7q3AeJqNqusDrm5xTK1Wzvfvetdpump",
    symbol: "RAFF",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "CTdf33YuD1dueyTmf8JNKHvC6yitsnPEpH9FqmRJpump",
    symbol: "POOF_CTDF",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER"],
    expectedScore: [300, 900],
    why: "mcap $0.04M, age 0d, liq $16k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
]
