// AUTO-GENERATED by scripts/corpus-discover.ts — review before merging
// Auto-labels use external DexScreener signals only (mcap, liq, age,
// 24h price change). They are intentionally CONSERVATIVE: SAFE only
// when overwhelming, RUG only on textbook dumps, CAUTION default. The
// engine sees on-chain data the labeller can't (top wallet %, LP burn,
// honeypot, GoPlus) so it has the final say — divergence between this
// label and the engine surfaces in the accuracy backtest.

import type { CorpusEntry } from "./corpus"

export const DISCOVERED: CorpusEntry[] = [
  {
    ca: "DzEdjffc7JkbkuDUkrf98njJ7KBVzabqUw5hej4Epump",
    symbol: "KILLGPT",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER", "RUG"],
    expectedScore: [300, 900],
    why: "mcap $0.81M, age 0d, liq $75k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "FU9s7E8zSczG1GXuy2u9n3VNgH6scJz9AprbxNtZpump",
    symbol: "SVE",
    expectedVerdict: "RUG",
    tolerated: ["DANGER"],
    expectedScore: [0, 400],
    why: "24h drop -96%, liq $4.0k — textbook rug.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "HDCaUHXLRsZCwdkgx7kM23ggojN5s6LagKLv8TEapump",
    symbol: "SCAMODEI",
    expectedVerdict: "RUG",
    tolerated: ["DANGER"],
    expectedScore: [0, 400],
    why: "24h drop -95%, liq $4.7k — textbook rug.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "DACYVx34V5aQaehN3MZGYxPfoyQYHZSnFAFw3T2Vbonk",
    symbol: "IMOUT",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER", "RUG"],
    expectedScore: [300, 900],
    why: "mcap $0.31M, age 7d, liq $71k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "7EV9ShfBB5NGtGcFVBQPVUVVtW3D6Emr3dPmh8rBpump",
    symbol: "PEEWELL",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $11.5k, age 2d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "E4xqRvahx9UdN5Unc2v5fmrkSK35UYZqi4gGJsbDpump",
    symbol: "SCAMPOWEL",
    expectedVerdict: "RUG",
    tolerated: ["DANGER"],
    expectedScore: [0, 400],
    why: "24h drop -92%, liq $4.2k — textbook rug.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "8SC3JXVf3UT5wEM9x48B1jVzWUeDgZiZdrrhN3zJpump",
    symbol: "SCAMDEX",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER", "RUG"],
    expectedScore: [300, 900],
    why: "mcap $0.11M, age 0d, liq $31k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "Hon2rHAiqkcDtUzL5gA2vjXPr7T1MPCK2UT2AHKCpump",
    symbol: "MAGA",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER", "RUG"],
    expectedScore: [300, 900],
    why: "mcap $16.45M, age 66d, liq $429k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "6qbh9jzbzHwKGH5gSXkWj5R7CjnbiVLRFs55cJx2pump",
    symbol: "SUICIDEGPT",
    expectedVerdict: "RUG",
    tolerated: ["DANGER"],
    expectedScore: [0, 400],
    why: "24h drop -94%, liq $4.1k — textbook rug.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "97tBZooZkwM1VfuCHYqhaAzZ2Y7TEAfVhJEW9MLbpump",
    symbol: "LUCA",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $6.7k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "3MZH44EYTvaStS4PtYrzkqa6FqzhhpBRXYBnnMAupump",
    symbol: "SCAMGUY",
    expectedVerdict: "RUG",
    tolerated: ["DANGER"],
    expectedScore: [0, 400],
    why: "24h drop -95%, liq $3.4k — textbook rug.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "3M3E4gf17jjeeZomna61H4rhMs5HVY8ypD7mUdZRpump",
    symbol: "WLD",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $10.4k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "DVtBMoubZfcqLyMzM6QbVMTGigGBsS9JAqUPfLXBpump",
    symbol: "USC",
    expectedVerdict: "RUG",
    tolerated: ["DANGER"],
    expectedScore: [0, 400],
    why: "24h drop -94%, liq $3.7k — textbook rug.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "CLVH4ob7p2afvG9fVSp5MQNw2rjXD7uR1PmfhiM7pump",
    symbol: "SCAMAI",
    expectedVerdict: "RUG",
    tolerated: ["DANGER"],
    expectedScore: [0, 400],
    why: "24h drop -94%, liq $3.7k — textbook rug.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "HYjNV846yU9rpG2ffMG8TaHJdBUWm1tPuttj2Dmkpump",
    symbol: "UNCSCAM",
    expectedVerdict: "RUG",
    tolerated: ["DANGER"],
    expectedScore: [0, 400],
    why: "24h drop -94%, liq $3.6k — textbook rug.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "3TYgKwkE2Y3rxdw9osLRSpxpXmSC1C1oo19W9KHspump",
    symbol: "BULL",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER", "RUG"],
    expectedScore: [300, 900],
    why: "mcap $4.86M, age 36d, liq $276k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "HdRFFy6Sm42rDAPLGRAZ1YymtpLukziwBrE9QGs4pump",
    symbol: "CRACKROCK",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER", "RUG"],
    expectedScore: [300, 900],
    why: "mcap $0.21M, age 0d, liq $36k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "12cNc76MT4H2F6CTndFNWpnoTwY6qz4vo2J9oGhFpump",
    symbol: "SKEM",
    expectedVerdict: "RUG",
    tolerated: ["DANGER"],
    expectedScore: [0, 400],
    why: "24h drop -95%, liq $3.5k — textbook rug.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "9F7YBM7emfWeJUxFKdH6ECYm6tB67869EcC4qmGzpump",
    symbol: "SCAM",
    expectedVerdict: "RUG",
    tolerated: ["DANGER"],
    expectedScore: [0, 400],
    why: "24h drop -95%, liq $3.2k — textbook rug.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "4df1wZoygsynEZ6XmpcoabrVwv7nBgjHLyCns5xApump",
    symbol: "BELKA",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER", "RUG"],
    expectedScore: [300, 900],
    why: "mcap $2.01M, age 3d, liq $134k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "BFiGUxnidogqcZAPVPDZRCfhx3nXnFLYqpQUaUGpump",
    symbol: "SPIKE",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER", "RUG"],
    expectedScore: [300, 900],
    why: "mcap $11.57M, age 20d, liq $391k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "8a5HrvhADXzBbJt95mc65fJ6YnPNuJjiDFSx9FYdpump",
    symbol: "BRUMUNZ",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER", "RUG"],
    expectedScore: [300, 900],
    why: "mcap $0.13M, age 0d, liq $29k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "BVzgTYPqV6ipEG4ixaQGfJvtYrs6kYJAt2HPBDMvpump",
    symbol: "SCAMGPT",
    expectedVerdict: "RUG",
    tolerated: ["DANGER"],
    expectedScore: [0, 400],
    why: "24h drop -95%, liq $3.3k — textbook rug.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "7fj85y28pKMndm4So66Szkb5GMGfLHFEkwsZdDx2pump",
    symbol: "NICE",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER", "RUG"],
    expectedScore: [300, 900],
    why: "mcap $0.14M, age 70d, liq $34k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "5gTPspC2ricuGWiYQ4Ghausg8fsq7uCrGgSVACatcoin",
    symbol: "CATCOIN",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER", "RUG"],
    expectedScore: [300, 900],
    why: "mcap $0.40M, age 4d, liq $59k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "59Ntdzm81rWKBshmuhJmuPFzczUy5e4zow2NNrpcDXTy",
    symbol: "SES",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER", "RUG"],
    expectedScore: [300, 900],
    why: "mcap $0.51M, age 0d, liq $35k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "3o1UuR1awdi7FtmVeCsWqBfp3cg26Z5RQhy6EwGNpump",
    symbol: "RESET",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER", "RUG"],
    expectedScore: [300, 900],
    why: "mcap $0.15M, age 0d, liq $30k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "G1UicqDY3mSN3PKWyFLUmqhekQ5k5MwdeXyz1VCTpump",
    symbol: "UNOSOL",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER", "RUG"],
    expectedScore: [300, 900],
    why: "mcap $0.41M, age 0d, liq $51k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "AABEk6vPpgLLoGGqRC4SrSTuZYywLyyPyfcAfvRzpump",
    symbol: "BOOBIO",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER", "RUG"],
    expectedScore: [300, 900],
    why: "mcap $0.06M, age 0d, liq $19k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "B3bJNmEdfMNGMf4D4P8GErzkbkdmuz1KFmn92iAhRCgC",
    symbol: "HIRO",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER", "RUG"],
    expectedScore: [300, 900],
    why: "mcap $0.06M, age 0d, liq $22k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "6Pt4PjcjSThQLyw5ye1qEtV877ubFSVqS8P4rC6Qpump",
    symbol: "BEE",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "HJ1Lk7qsamHNkuoNMhZbzMRGSHswstw5LCLvacj6pump",
    symbol: "SCAMMOR",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "BwUgJBQffm4HM49W7nsMphStJm4DbA5stuo4w7iwpump",
    symbol: "ELO",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER", "RUG"],
    expectedScore: [300, 900],
    why: "mcap $0.07M, age 2d, liq $22k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "EcnakfbboQMVPZj8ynfALxngQ3Y6MnVrfr5A5HdPpump",
    symbol: "SCAMTRUMP",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "6HXCCASZxmv5jnExJDoe7TTQJMu6kfctRotVmtHGpump",
    symbol: "ELUN",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER", "RUG"],
    expectedScore: [300, 900],
    why: "mcap $0.09M, age 24d, liq $32k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "tUAxFzG84g9X8rXkk2KWgrKdaVSsc59KrDEPiv3pump",
    symbol: "DOGMCOIN",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $7.6k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "8RFoNyED7nx8LCS2mAehsocGqViZUsHb784KUA9UD6p2",
    symbol: "OPENLIE",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER", "RUG"],
    expectedScore: [300, 900],
    why: "mcap $0.06M, age 0d, liq $22k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "HkdF4pYRnPfwRPJ7pXzh3MuzMeqz7rnkzfG5qTDhpump",
    symbol: "MAKTS",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $0.0k — ultra-thin liquidity, exit risk.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "4mYUGV7AaMw5HFefpCrsjotnu99KZKn4VKxYYZwdpump",
    symbol: "BEAR",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "4syGYCWUrRU8po4DQZgPgpzhZG8nZXQoGu4Jf7fppump",
    symbol: "SCAMUSK",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "HmBdm8vbisABUjkxms6ZUnoaXbfwFM6ymxShWfAENaoi",
    symbol: "EITHER",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER", "RUG"],
    expectedScore: [300, 900],
    why: "mcap $26.47M, age 35d, liq $438k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "9oxGicd5KXNcthYM6yD23X9zcznQVnHjrAEN38fFpump",
    symbol: "BIOLLM",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER", "RUG"],
    expectedScore: [300, 900],
    why: "mcap $0.45M, age 56d, liq $75k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "96qJmCKtj9E5fiehGToQ69bwyiw9q86y7q4gAGznpump",
    symbol: "MESSI",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "9QLrH5vE51uNavc9VWAA5GgjXzXDLNk1va6iWYJyEPt3",
    symbol: "WXG",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER", "RUG"],
    expectedScore: [300, 900],
    why: "mcap $0.12M, age 135d, liq $20k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "3ZcEqsgJZxy5pER4XBfa2UbjBmRAgG96nUrTATfMpump",
    symbol: "WHITEBOY",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 5d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "APJ8ovk6mqScmtezgtMcMGxkiB5PGwcLmgz343Rkpump",
    symbol: "SCAMCOIN",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "7soYuSPe1LaJ9V37W7ZGDB5Xwxi41LUWjRT3AEQGpump",
    symbol: "WOLVERINE",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $11.6k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "52nVoVk3BimAtvu2y9q1gnxqgR8pmjcc3v3byGnCuBa",
    symbol: "SCUBA",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER", "RUG"],
    expectedScore: [300, 900],
    why: "mcap $0.34M, age 54d, liq $68k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "GC3T8XboCofhBPs5U48DJgp6cxxMeu1CBZXgB2dopump",
    symbol: "LITH",
    expectedVerdict: "RUG",
    tolerated: ["DANGER"],
    expectedScore: [0, 400],
    why: "24h drop -88%, liq $5.0k — textbook rug.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "2KztYDCf3vYtm8QHibXt7uxdjt47oxEi8ZTihEYApump",
    symbol: "FKM",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $7.5k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "CCuxEcR8EM8AJbBKMrSUErzwMtxGSo49xnqMJntvpump",
    symbol: "TIM",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "6DZr2Q87FVSzQ4EjyvWTph1VhtjtPaEyGksVUoxGpump",
    symbol: "ALTMAN",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "Aq4jqvy6bBjNccXdim54TWVNRpDw4Dkw4PYWMj3Mpump",
    symbol: "TRUTHCOIN",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "FKF2G1C7gWQnUySzGcxWwTa7EGKevHMK7JNy1ejopump",
    symbol: "8647",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "CU8dnZ4Vv7G1QdtTxnykL9o4xJDhaDVCjES4vsXhXxoD",
    symbol: "TMT",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $5.7k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "3nhngTxdduSp73koJWCqsEux2JP5ACHtLYkxLxYfpump",
    symbol: "BACK",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "UshSHTbdyCRBuPvxXx8SL5PDsKSB3BS7X71TC1Gpump",
    symbol: "PAY",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "UBYLGDdZc1HNspordhmn5UCA9WxweTwCp9AYDoQscwu",
    symbol: "CWF",
    expectedVerdict: "RUG",
    tolerated: ["DANGER"],
    expectedScore: [0, 400],
    why: "24h drop -95%, liq $3.1k — textbook rug.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "AwuYdKH1yynRKxWcZMVfXMyh3ySgX7RHjq6q9h5zbrrr",
    symbol: "PEPE",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "8m1RhToZLEEYiE3nBsyHvJRr7fPh5McMMHiiC9LAKqyX",
    symbol: "PONZI",
    expectedVerdict: "RUG",
    tolerated: ["DANGER"],
    expectedScore: [0, 400],
    why: "24h drop -86%, liq $5.6k — textbook rug.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "95b6yjAbankmzFu26xEvowHuGqctf4q56GRQZcGEpump",
    symbol: "APOLLO",
    expectedVerdict: "RUG",
    tolerated: ["DANGER"],
    expectedScore: [0, 400],
    why: "24h drop -91%, liq $4.3k — textbook rug.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "BMRMVjoA3tf4B3fByMayWbBQEjFTtxQw5Awf3Upvpump",
    symbol: "HIRO_BMRM",
    expectedVerdict: "RUG",
    tolerated: ["DANGER"],
    expectedScore: [0, 400],
    why: "24h drop -96%, liq $3.2k — textbook rug.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "5p2Uoo171giWk3SU2PaqkhPaJQv6aAasR2vDxs5jpump",
    symbol: "RETA",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "CPqPxhXo4pWyfLa21G2rR1YxUqdaiJgKjFRgGmxnpump",
    symbol: "USD1",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "9D9N9cPgwL856jJuCo4EhrAicHjBNWwucopFZEvMpump",
    symbol: "GORGON",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $6.9k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "AkPrQJfU6MGUdcT2JtZA1jJMcgZ1bjidzLicwJuHpump",
    symbol: "KOTUS",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $6.3k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "GhEG5jiw3sCjS8rR5t1RPLdvo5nk89Qb3CAeyCDvpump",
    symbol: "UP",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $11.2k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "5ZSi1AV7Zg2RU3EHjJ2FroW3GXWHtFX8CtDCW933pump",
    symbol: "SC",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "7hTNy5n3NtEAAeuc58UkuSCBiSvyHvyzxzVKf7sepump",
    symbol: "FEETALIK",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "G8gDPKuk2FwddhDjSGhQ1ZuKeNAPUez2Cr3VUN35pump",
    symbol: "BEAR_G8GD",
    expectedVerdict: "RUG",
    tolerated: ["DANGER"],
    expectedScore: [0, 400],
    why: "24h drop -88%, liq $4.9k — textbook rug.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "arDE6soJwuHKsZUbJsXCkSKzUNzi8dVETRhPEySpump",
    symbol: "GECKO",
    expectedVerdict: "RUG",
    tolerated: ["DANGER"],
    expectedScore: [0, 400],
    why: "24h drop -95%, liq $3.2k — textbook rug.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "5HV956n7UQT1XdJzv43fHPocest5YAmi9ipsuiJx7zt7",
    symbol: "MEMECOIN",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER", "RUG"],
    expectedScore: [300, 900],
    why: "mcap $0.06M, age 379d, liq $45k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "43VWkd99HjqkhFTZbWBpMpRhjG469nWa7x7uEsgSH7We",
    symbol: "STNK",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER", "RUG"],
    expectedScore: [300, 900],
    why: "mcap $4.04M, age 521d, liq $284k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "zGh48JtNHVBb5evgoZLXwgPD2Qu4MhkWdJLGDAupump",
    symbol: "RETIRE",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER", "RUG"],
    expectedScore: [300, 900],
    why: "mcap $3.96M, age 561d, liq $569k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "1Qf8gESP4i6CFNWerUSDdLKJ9U1LpqTYvjJ2MM4pain",
    symbol: "PAIN",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER", "RUG"],
    expectedScore: [300, 900],
    why: "mcap $3.85M, age 433d, liq $2443k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "AyrQpt5xsVYiN4BqgZdd2tZJAWswT9yLUZmP1jKqpump",
    symbol: "JOBCOIN",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER", "RUG"],
    expectedScore: [300, 900],
    why: "mcap $3.84M, age 378d, liq $297k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "H74CYmXgMkYHYuSRsZt6RJb4NYp2u72Vw8BS5huApump",
    symbol: "LMAO",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER", "RUG"],
    expectedScore: [300, 900],
    why: "mcap $1.82M, age 192d, liq $182k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "mpoxP5wyoR3eRW8L9bZjGPFtCsmX8WcqU5BHxFW1xkn",
    symbol: "POX",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER", "RUG"],
    expectedScore: [300, 900],
    why: "mcap $1.77M, age 608d, liq $86k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "6yjNqPzTSanBWSa6dxVEgTjePXBrZ2FoHLDQwYwEsyM6",
    symbol: "CHUD",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER", "RUG"],
    expectedScore: [300, 900],
    why: "mcap $1.77M, age 723d, liq $307k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "9raUVuzeWUk53co63M4WXLWPWE4Xc6Lpn7RS9dnkpump",
    symbol: "V2EX",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER", "RUG"],
    expectedScore: [300, 900],
    why: "mcap $1.73M, age 295d, liq $182k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "Bo9jh3wsmcC2AjakLWzNmKJ3SgtZmXEcSaW7L2FAvUsU",
    symbol: "LIBRA",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER", "RUG"],
    expectedScore: [300, 900],
    why: "mcap $1.17M, age 437d, liq $5488k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "7hWcHohzwtLddDUG81H2PkWq6KEkMtSDNkYXsso18Fy3",
    symbol: "CAT",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER", "RUG"],
    expectedScore: [300, 900],
    why: "mcap $0.33M, age 852d, liq $152k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "69G8CpUVZAxbPMiEBrfCCCH445NwFxH6PzVL693Xpump",
    symbol: "XAVIER",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER", "RUG"],
    expectedScore: [300, 900],
    why: "mcap $1.11M, age 547d, liq $145k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "HtTYHz1Kf3rrQo6AqDLmss7gq5WrkWAaXn3tupUZbonk",
    symbol: "KORI",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER", "RUG"],
    expectedScore: [300, 900],
    why: "mcap $1.11M, age 350d, liq $244k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "rizo34MUwbCBqpSTSfnEktdWB4CTByqqYh8zBxL3WAR",
    symbol: "RIZO",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER", "RUG"],
    expectedScore: [300, 900],
    why: "mcap $0.79M, age 635d, liq $196k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "H2c31USxu35MDkBrGph8pUDUnmzo2e4Rf4hnvL2Upump",
    symbol: "SHOGGOTH",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER", "RUG"],
    expectedScore: [300, 900],
    why: "mcap $0.79M, age 556d, liq $253k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "9tqjeRS1swj36Ee5C1iGiwAxjQJNGAVCzaTLwFY8bonk",
    symbol: "ANI",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER", "RUG"],
    expectedScore: [300, 900],
    why: "mcap $0.79M, age 288d, liq $177k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "Fch1oixTPri8zxBnmdCEADoJW2toyFHxqDZacQkwdvSP",
    symbol: "HARAMBE",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER", "RUG"],
    expectedScore: [300, 900],
    why: "mcap $0.74M, age 832d, liq $257k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "8vGr1eX9vfpootWiUPYa5kYoGx9bTuRy2Xc4dNMrpump",
    symbol: "FAPCOIN",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER", "RUG"],
    expectedScore: [300, 900],
    why: "mcap $0.73M, age 192d, liq $86k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "F2k82EcxLtzekq1bfoGVdgp6EXZ5dLT1jE7g3LvQpump",
    symbol: "PENGO",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER", "RUG"],
    expectedScore: [300, 900],
    why: "mcap $0.73M, age 200d, liq $74k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "bobaM3u8QmqZhY1HwAtnvze9DLXvkgKYk3td3t8MLva",
    symbol: "BOBAOPPA",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER", "RUG"],
    expectedScore: [300, 900],
    why: "mcap $2.36M, age 759d, liq $28k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "AVLhahDcDQ4m4vHM4ug63oh7xc8Jtk49Dm5hoe9Sazqr",
    symbol: "SOLAMA",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER", "RUG"],
    expectedScore: [300, 900],
    why: "mcap $0.55M, age 847d, liq $130k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "Ai4CL1SAxVRigxQFwBH8S2JkuL7EqrdiGwTC7JpCpump",
    symbol: "AWR",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER", "RUG"],
    expectedScore: [300, 900],
    why: "mcap $0.53M, age 477d, liq $103k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "4bY7N2hPq4aHQJwbhawceNqS5ksyQAayiLEsjNMwpump",
    symbol: "COMAT",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER", "RUG"],
    expectedScore: [300, 900],
    why: "mcap $0.35M, age 164d, liq $56k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "HwPtbFpd3VTe3tfyosoVtPf9WPuSk5gAKkN5xp6Npump",
    symbol: "",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER", "RUG"],
    expectedScore: [300, 900],
    why: "mcap $0.35M, age 527d, liq $109k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "Faf89929Ni9fbg4gmVZTca7eW6NFg877Jqn6MizT3Gvw",
    symbol: "WOLF",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER", "RUG"],
    expectedScore: [300, 900],
    why: "mcap $0.34M, age 683d, liq $137k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "GQe8DCQTBkuX5E2sjvwuKDZsjGYhU8k3DN5dkSbQLfqJ",
    symbol: "BURN",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $6.5k — ultra-thin liquidity, exit risk.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "CF5VehjuZvxZZQFP5tybGra6ts574FAwt6Z7GuX9pump",
    symbol: "ELLA",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER", "RUG"],
    expectedScore: [300, 900],
    why: "mcap $0.27M, age 316d, liq $40k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "EJPtJEDogxzDbvM8qvAsqYbLmPj5n1vQeqoAzj9Yfv3q",
    symbol: "BOZO",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER", "RUG"],
    expectedScore: [300, 900],
    why: "mcap $0.28M, age 850d, liq $15k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "Gqqdgfkn7bcsuBQZEk9oMBkqCv1bRXvPmTLs3sQ9pump",
    symbol: "PEPONK",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER", "RUG"],
    expectedScore: [300, 900],
    why: "mcap $0.26M, age 116d, liq $43k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "9WPTUkh8fKuCnepRWoPYLH3aK9gSjPHFDenBq2X1Czdp",
    symbol: "SELFIE",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER", "RUG"],
    expectedScore: [300, 900],
    why: "mcap $0.26M, age 716d, liq $151k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "21rweMLGYeMNonHW7H3xa5py17X6ZFRcHirCp9inRBQA",
    symbol: "IQ50",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER", "RUG"],
    expectedScore: [300, 900],
    why: "mcap $0.20M, age 773d, liq $120k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "AYABiqKuTh9Va5Aqc6AujFevHwDGmECGQiFmKW5g3K4Z",
    symbol: "LONG",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER", "RUG"],
    expectedScore: [300, 900],
    why: "mcap $0.19M, age 764d, liq $43k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "F9CpWoyeBJfoRB8f2pBe2ZNPbPsEE76mWZWme3StsvHK",
    symbol: "PEPE_F9CP",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER", "RUG"],
    expectedScore: [300, 900],
    why: "mcap $0.12M, age 1193d, liq $61k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "CJUrENDAuSm4FxxziUgftnUJqqXjm4VL1zhJgwXupump",
    symbol: "HENRY",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER", "RUG"],
    expectedScore: [300, 900],
    why: "mcap $0.16M, age 2d, liq $45k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "38fXPsdJz2jo2KE1GM5b6N8f7d4ARDDnLyB8EH2npump",
    symbol: "BABYAI16Z",
    expectedVerdict: "RUG",
    tolerated: ["DANGER"],
    expectedScore: [0, 400],
    why: "24h drop -93%, liq $3.0k — textbook rug.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "FG3nFQMjs2b3igfttsSstsxMWwsWaUp495fSPU3Gpump",
    symbol: "PFP",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER", "RUG"],
    expectedScore: [300, 900],
    why: "mcap $0.05M, age 569d, liq $18k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "6AVAUKa9uxQpruHZUinFECpXEh1usRVtzQWK8N2wpump",
    symbol: "SCAM_6AVA",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER", "RUG"],
    expectedScore: [300, 900],
    why: "mcap $5.50M, age 1d, liq $320k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "USD1ttGY1N17NEEHLmELoaybftRBUSErhqYiQzvEmuB",
    symbol: "USD1_USD1",
    expectedVerdict: "SAFE",
    tolerated: ["CAUTION"],
    expectedScore: [750, 1000],
    why: "mcap $158M, age 241d, liq $9.9M — established blue-chip.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "orcaEKTdK7LKz57vaAYr9QeNsVEPfiu6QeMU1kektZE",
    symbol: "ORCA",
    expectedVerdict: "SAFE",
    tolerated: ["CAUTION"],
    expectedScore: [750, 1000],
    why: "mcap $102M, age 844d, liq $1.0M — established blue-chip.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "4jqoY1hhHPJFFCt3UcXJe7eVJsHn7ArphnGk5VBBJ4rr",
    symbol: "GDER",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "DTfN4DotNupzDbqpg6dX4jfXekB5vVkePxjuyivJpump",
    symbol: "BEE_DTFN",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER", "RUG"],
    expectedScore: [300, 900],
    why: "mcap $0.11M, age 0d, liq $32k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "7NCaYBNGLjtRyj8AkvTmUdjH18fkSURWNqcZCWQZVjVC",
    symbol: "RCSC",
    expectedVerdict: "RUG",
    tolerated: ["DANGER"],
    expectedScore: [0, 400],
    why: "24h drop -100%, liq $0.1k — textbook rug.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "BZ1avfKCfJKNgsDeXHNkPku5GcWVzi2Aw2HesHcrpump",
    symbol: "LUCA_BZ1A",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER", "RUG"],
    expectedScore: [300, 900],
    why: "mcap $0.09M, age 0d, liq $28k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "GU8u7Ebp583iEZJHTvYtEntM8nEaqpA3RJiWfRJo2ZQW",
    symbol: "XCHAT",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "2EnVBvD1FA7hX3B81K9kFfcyNz44m75WQYMrXAXUf1jw",
    symbol: "GOAL",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "2fdRrEgb5tRK3RwAr9bgoKSXgP8xfxKdnZmbeHT7DRTh",
    symbol: "GDER_2FDR",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $0.1k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "hhZJNUeEQcfeGwb3HSCwZczjBwjit5GktbmXPNVtYWX",
    symbol: "HRP",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $0.1k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "DUVHLxLFkC5Ks1poMkmiHqhKhwPdbaXMV2c3GRshmha1",
    symbol: "CR7",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "8J2AuCgwW5W68K6B2rDqZpurWQLLjGG2jLmenu1gUrfv",
    symbol: "RCSC_8J2A",
    expectedVerdict: "RUG",
    tolerated: ["DANGER"],
    expectedScore: [0, 400],
    why: "24h drop -99%, liq $0.0k — textbook rug.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "35AC1pdHfpxAGEscDGieia99g9npD71A1Yc7th4hwQoD",
    symbol: "SCAM_35AC",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "ciZhNMrdcEACxwuj23mofjCixZ5dh77fU2xfoj1oHRx",
    symbol: "GOAL_CIZH",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 1d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "HBDViVBPEqRYrCsF4qbFmF98M7KwmuPup7eFz5vXpump",
    symbol: "QOTUS",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER", "RUG"],
    expectedScore: [300, 900],
    why: "mcap $0.04M, age 462d, liq $15k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "8RgCnFUJa4FAConij8dyetMrbdU7zQKrjCvxCVGk5Ek2",
    symbol: "GDER_8RGC",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $0.1k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "CgrPuM6TuiQtrtdqbHAZoncmKJ2XiQw1c4QWWGxKj45L",
    symbol: "RCSC_CGRP",
    expectedVerdict: "RUG",
    tolerated: ["DANGER"],
    expectedScore: [0, 400],
    why: "24h drop -97%, liq $0.0k — textbook rug.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "9jkEmTxtj1pFchbQRNWKWBLYBje6GdT7zsAtSWCVc44Q",
    symbol: "MEMEMEMORY",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $0.1k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "CnyZhb9SF8xLJ4pMimgNVSfKNQcox8WnkUhhbm87K4VV",
    symbol: "OVPP",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "FfqMruBcAY8hnz1My9aueFEwp6jKegduESUWtXXE2Lvg",
    symbol: "ASTEROID",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 1d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "DURxAQdFPmUg2CzDWYCuVDxL2vAPhQManMaoP4GoYyPN",
    symbol: "PROS",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $0.1k, age 1d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "8wTQqaf4Fjop1v2hui8o1G4BoW94HGH32nKLAjQ3BmzR",
    symbol: "GDER_8WTQ",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "54Uu4ovrNha2GubRiomfgeWSv38PTF9ZDoPScHJGNM75",
    symbol: "GDER_54UU",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $0.1k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "GKY46UqorCSuu984t4ZjaiDgf97pGMFtEUNfGgLqpump",
    symbol: "SCAMMURZ",
    expectedVerdict: "RUG",
    tolerated: ["DANGER"],
    expectedScore: [0, 400],
    why: "24h drop -96%, liq $4.2k — textbook rug.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "kMKX8hBaj3BTRBbeYix9c16EieBP5dih8DTSSwCpump",
    symbol: "AFK",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER", "RUG"],
    expectedScore: [300, 900],
    why: "mcap $2.74M, age 93d, liq $166k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "31zYBHmHiQ1JNnHY8L2tnyzxwAjSBa1uNgSnkT2YRN9y",
    symbol: "WLD_31ZY",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "7uhtZyHfFAyCyqPrQgRBQiXJLNLSDHZPTZoXDziHy3iB",
    symbol: "PRESPAX",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "FZqjTtgjTRUj5Y7PD1TVN4cCom5jmw1q6Xy148EyhKFX",
    symbol: "PSTR",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "4y1gkKzCb4qAiH8pH8ft2xvezf6sazurmYDajWXwpump",
    symbol: "CREATURES",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER", "RUG"],
    expectedScore: [300, 900],
    why: "mcap $0.36M, age 0d, liq $63k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "9b9H3GCm72NajcJizDxattZxg3hgA7m1Rm5zsFzthrt6",
    symbol: "SCAM_9B9H",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "HGEdtFd7DBeoYYufq6jEsCQsSsqDvCfLVcCwBYLEAgRF",
    symbol: "SCAM_HGED",
    expectedVerdict: "RUG",
    tolerated: ["DANGER"],
    expectedScore: [0, 400],
    why: "24h drop -94%, liq $0.0k — textbook rug.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "FUW25PNvN5jSavdZjrXVrwVgob94iyxoB55WMZdEBdwF",
    symbol: "GOAL_FUW2",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "9RZ4NfBfdBBcM7y2848vGKSSwKJBFVT7zQgXiwL8jZQ4",
    symbol: "DUNALD",
    expectedVerdict: "RUG",
    tolerated: ["DANGER"],
    expectedScore: [0, 400],
    why: "24h drop -100%, liq $0.0k — textbook rug.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "7mJ4tTSsL63fa69qkdDbw4fhx6SPzfA8uS4bVisStfi4",
    symbol: "BEEKEEPER",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER", "RUG"],
    expectedScore: [300, 900],
    why: "mcap $0.04M, age 0d, liq $18k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "Ha8bNbwp1B3zwBYfi2YcccWD13x3CRshPSHv1xfrt3iv",
    symbol: "PRESPAX_HA8B",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "CEVjDwPxdHx3uuBNyASuWQmeBa57QJQ3PCA3UsNNjX6D",
    symbol: "ENRON",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER", "RUG"],
    expectedScore: [300, 900],
    why: "mcap $0.50M, age 448d, liq $54k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "c3ARD1SjjzUoXcFhY8oFiitu9V46tCdhojmuHTnevxF",
    symbol: "DBEET",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $0.2k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "6d6LCaXXeWZscKB4qxnwTyHBF3zYDF5MrPV3bjdDbonk",
    symbol: "BNX",
    expectedVerdict: "RUG",
    tolerated: ["DANGER"],
    expectedScore: [0, 400],
    why: "24h drop -93%, liq $3.5k — textbook rug.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "35e4ohP3VSyZA8WLmo8wVRkLwjQ3L64XzVL1T6S6hstG",
    symbol: "SCAM_35E4",
    expectedVerdict: "RUG",
    tolerated: ["DANGER"],
    expectedScore: [0, 400],
    why: "24h drop -100%, liq $0.0k — textbook rug.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "G6YuEU977AZMWnsacYDuUnAvrvMi8n8rd8wodCTVfWP3",
    symbol: "RCSC_G6YU",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "86YgpPC64P42imZ28n1qZUi9nLuTvetKwz8NrSMivHpA",
    symbol: "SCAM_86YG",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 1d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "EhmghXLRdLtsri9hvpRZ73zaHZ7YcXh86BADzxwjSFkQ",
    symbol: "MONAUNC",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "2DY7JMiLA6VvSJ2WmKGA7FHy1sHgrVjy91yd4q8o23JJ",
    symbol: "HRP_2DY7",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "6pwRXyNB6vZrGGJYromTp9zs87uBhposVMngE38uG3cL",
    symbol: "RCSC_6PWR",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $2.1k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "2bmXSqd8C4VBUcsDeKuDdRYFJviEBUp52rejeKFeaeiz",
    symbol: "MEGA",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER", "RUG"],
    expectedScore: [300, 900],
    why: "mcap $0.08M, age 0d, liq $66k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "FHMpPNaPxQJcyCJBYF7LddH9up2wDPnoGUdi1H6CFcZ6",
    symbol: "OPENLIE_FHMP",
    expectedVerdict: "RUG",
    tolerated: ["DANGER"],
    expectedScore: [0, 400],
    why: "24h drop -100%, liq $0.1k — textbook rug.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "CUi5ULzTKY9P93cjkCVD8HrB6txw2v4yzQuwBJgipump",
    symbol: "PARANOID",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER", "RUG"],
    expectedScore: [300, 900],
    why: "mcap $0.03M, age 0d, liq $16k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "CPq6d37dyMQYR5V4cadySVagHn7VMceRgfMRZZ1xNEiv",
    symbol: "SCAM_CPQ6",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "5nrLD7JDem6LiJNRP43NjLAkE8WFc2WZYZafBW42smqf",
    symbol: "STOCKMAN",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER", "RUG"],
    expectedScore: [300, 900],
    why: "mcap $0.09M, age 1d, liq $29k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "AqEK6ioLagvjsDMfLhPtijWG6ZC8nHY32TP2gp36yoZe",
    symbol: "GOAL_AQEK",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "HymvY6qZXDLCRuteuATpFJYgLLTJqwbGR41Ut9NSpump",
    symbol: "MEMEMEMORY_HYMV",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $11.3k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "DXcwhg1MwrResr1CoaBuhnnHmcx222ntZAgRd28Jpump",
    symbol: "SCAM_DXCW",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER", "RUG"],
    expectedScore: [300, 900],
    why: "mcap $0.20M, age 1d, liq $41k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "9UnkAJ2A8jxKTDGzM11zPkbEgA8JVU82NckfsshAp6cs",
    symbol: "GDER_9UNK",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "DCNEi1eFWEFA7MQYkh8kSDeZ3bgja453j1sQ3Rn1pump",
    symbol: "ANNIE",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $11.4k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "pY4dq8Fz3hSeRNdWZ3nJM623TreF1S1isi19UWrpump",
    symbol: "SP500",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $3.2k — ultra-thin liquidity, exit risk.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "G5FYxYQCDNMSBBspnDGzRYLDdwE8stNJ7scBBme33eh2",
    symbol: "SCAM_G5FY",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R",
    symbol: "RAY",
    expectedVerdict: "SAFE",
    tolerated: ["CAUTION"],
    expectedScore: [750, 1000],
    why: "mcap $201M, age 1247d, liq $4.0M — established blue-chip.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "STrikemJEk2tFVYpg7SMo9nGPrnJ56fHnS1K7PV2fPw",
    symbol: "STRIKE",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER", "RUG"],
    expectedScore: [300, 900],
    why: "mcap $0.13M, age 452d, liq $54k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "9yYkQDA9r9JjngQpVqxF4cYBHysgkVvMEnRBomBqaEcv",
    symbol: "HRP_9YYK",
    expectedVerdict: "RUG",
    tolerated: ["DANGER"],
    expectedScore: [0, 400],
    why: "24h drop -86%, liq $0.0k — textbook rug.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "AGkg5XnnGHysHbSfRotWokUsAU7QqN7cL4EraHbhzUrz",
    symbol: "AIB",
    expectedVerdict: "RUG",
    tolerated: ["DANGER"],
    expectedScore: [0, 400],
    why: "24h drop -100%, liq $0.0k — textbook rug.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "2rjcQydrkLN4xBgGRinobWYBJhPBz4BAjyRgEyMkkAhP",
    symbol: "RCSC_2RJC",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "Gow1ASA17DSMBemxyGbT9spmvr8n1HQtZjupoqTjqtKg",
    symbol: "HRP_GOW1",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER", "RUG"],
    expectedScore: [300, 900],
    why: "mcap $0.49M, age 0d, liq $277k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "D6xWgRCSHoMEB5fqPwk3p6Stxirn5ytm2WwboSTTx4oE",
    symbol: "PYBOBO",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $0.0k — ultra-thin liquidity, exit risk.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "9nV5ZAVm1pyqamdMTv1MSuxXBHMChtN89JdS2gUCPPF4",
    symbol: "GMAR",
    expectedVerdict: "RUG",
    tolerated: ["DANGER"],
    expectedScore: [0, 400],
    why: "24h drop -95%, liq $0.0k — textbook rug.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "41wPz6nY8m4vkzVRUVCcwUAyDdi9ae7Aj6aqaoFpLkjr",
    symbol: "CR7_41WP",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "By31WYNbKcYkrwWQyBzLMMtRbLWZfUkW2G4FLYjMuweK",
    symbol: "PROS_BY31",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "CnjPKwrftjm7Tr3t4GyfFjoqQ2tSbnHMCbvCAvVKe72z",
    symbol: "RCSC_CNJP",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "Dju63Pa6LCR8gnxCqFQW6DQFv1a3UKSD971jVTakk78J",
    symbol: "VESTING",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $0.1k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "3WZYytFXiPAZ7CYXw2BqevhSkcNTuAziwSsEXkkNbqtc",
    symbol: "HRP_3WZY",
    expectedVerdict: "RUG",
    tolerated: ["DANGER"],
    expectedScore: [0, 400],
    why: "24h drop -91%, liq $0.0k — textbook rug.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "GWfuPWmKjviN3jHXZyZxUdxLqNaL3n5rmzZUAZJFH1dN",
    symbol: "SCAM_GWFU",
    expectedVerdict: "RUG",
    tolerated: ["DANGER"],
    expectedScore: [0, 400],
    why: "24h drop -99%, liq $0.0k — textbook rug.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "6RB1xAWMVy3aju243KWsH8kqWKFYCKGuEJyKNvxut3V4",
    symbol: "CREATURES_6RB1",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "D8nMWEaawrwhKSzqB27HvjJbDZH66NsHj1uQujenvrDS",
    symbol: "ILHEN",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $0.1k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "Aaqmx8ZTgDmnNfS7QEKvRWZjwvp4xFCJ3QTMn1r8jMfG",
    symbol: "SCAM_AAQM",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "vRseBFqTy9QLmmo5qGiwo74AVpdqqMTnxPqWoWMpump",
    symbol: "VERSE",
    expectedVerdict: "CAUTION",
    tolerated: ["SAFE", "DANGER", "RUG"],
    expectedScore: [300, 900],
    why: "mcap $2.85M, age 323d, liq $547k — mid-cap default (engine has final say).",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "GKiqDc8apRFsBkYBKGCT5Wsbacz9ixoNYSnkshoWpump",
    symbol: "JFDS",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $2.9k — ultra-thin liquidity, exit risk.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "7qL1hXMrfnLjjx91Cw7MFhhnH1YVj7pUaGHCEF7tL57U",
    symbol: "PP",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $0.1k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "DLizRmzmzLmuEN7S9QLCdotquQuSgupcELScsWC3AU69",
    symbol: "GDER_DLIZ",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "5h6UkZxYi5z1NUWuw3mLRpXuFsRcEiR4M5EZbdAE1cLx",
    symbol: "SES_5H6U",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "4H8URz86pnuMq5YyGvUA5W2w3d2AtVrM5gpnnpfTVBUi",
    symbol: "OPEN",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "GnZarwNbg9U1FJAyjsRJrb8EBZCHDyFUHHBCRUEbrHFW",
    symbol: "AIB_GNZA",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "6ZmGefehnaweyGv6Xmn2em44T78Uqc41kqbSyH7JBAez",
    symbol: "PRESPAX_6ZMG",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "GKGcyt1xsQtqaWQu6GKb8VFXRTkb5UgN3W6xdyY89D5s",
    symbol: "RCSC_GKGC",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "247DUfhqdPVvVgjq6zhjXmK9V4pCEr5EpEosgUVsMaTn",
    symbol: "GMAR_247D",
    expectedVerdict: "RUG",
    tolerated: ["DANGER"],
    expectedScore: [0, 400],
    why: "24h drop -100%, liq $0.0k — textbook rug.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "GQfHEf7nRe9PZ8DVnYQopZvpKbKysGDZ6gSSZRyxRZRT",
    symbol: "DAND",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "2qTrWtpVhz6WzNWi85rkAHPp54VcUjBaHzBKW2QxRbSR",
    symbol: "WLD_2QTR",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "3jgqeVGAgdsD5GAQS7LtVbprVB9vvwTvTGA7Bbd6VVRr",
    symbol: "FAX",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 0d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "315reUAaSQHoHEzXwSbdWyxtaBiQNmzjd5FH4wvkrdBy",
    symbol: "SCAM_315R",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $0.0k, age 1d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
  {
    ca: "6m28N1fAjyNpgS35oQC2yHy97EhD1asLGfkmkaYVowhJ",
    symbol: "RCSC_6M28",
    expectedVerdict: "DANGER",
    tolerated: ["RUG", "CAUTION", "SAFE"],
    expectedScore: [100, 600],
    why: "liq $4.0k, age 1d — fresh-launch thin liquidity.",
    source: "external",
    skipFixture: true, // pending first capture
  },
]
